### ISSUE TITLE
Right behaviour or bug?

### ISSUE THREAD

**Issue by glundgren** [robinbortlik/validates_overlap#20]
Hey,

I'm using your gem in a project, very handy, but i found a behaviour that i don't know if its a feature or a bug.

Let's say you have an app where we have a user parent, that has children. The children users can open and then close multiple 'movements', in this case the scope is the children_id, and a different children can overlap another, but can't overlap themselves.

Ok, i achieve that with something like this:

```
validates :start_date, :end_date, :overlap => { :scope => 'child_id'}
```

But if i try to create a movement in a time before my last movement, it says it overlaps, even if i didn't set the end_date yet. For example, i set a movement  with start_date at 01/01/2015 10AM and close it at end_date 01/01/2015 11AM, then if for some reason i need to create another movement at 01/01/2015 8AM, with end_date not set, it says start_date overlaps.

It's kind of a ultra-safe behaviour to avoid overlap or a scenario that was not planned before? Any tips how can i achieve that?

Rails 4.1.5 and Ruby 2.1.x

**Comment by robinbortlik** [comment]
@glundgren can I close this issue?
