### ISSUE TITLE
How to get conflicting records?

### ISSUE THREAD

**Issue by milankubin** [robinbortlik/validates_overlap#31]
I would like to reference, as part of the validation error message, which records are conflicting.
Let's say: User attends event x, but is assigned to y in the same slot. In order to make it easier to resolve the conflict, I would want to show information (id, start, enddate, desc) of the record x .
Is this possible?

**Comment by robinbortlik** [comment]
Hi @milankubin ,

the gem actually does not provide this functionality. But from what I see, it should not be hard to change the logic little bit and implement it. 
Simply fork this gem, and on this line https://github.com/robinbortlik/validates_overlap/blob/master/lib/validates_overlap/overlap_validator.rb#L39 change ```exists?``` to ```where``` . Then you need to store value returned from ```find_crossed``` method  to the ```record``` variable. You can simply create some attribute accessor. 

Is it clear? Let me know if you will need some help.

**Comment by robinbortlik** [comment]
Hi @milankubin any progress?

**Comment by milankubin** [comment]
Wasn't on my  (client's ;)) priority list, somewhere within the next week
weeks I will be addressing this feature!

**Comment by johnmosesman** [comment]
@robinbortlik Is this something you're considering? I think a few people (myself included) would appreciate this. Even if just for debugging purposes.

**Comment by stricte** [comment]
@johnmosesman I know that using send is considered as bad practice, but you can implement simple method on your model to find crossed objects:

```ruby
def find_crossed
   attributes = { attributes: [:start_at, :stop_at] }
   scope = 'place_id'

   ov = OverlapValidator.new(atributes)

   ov.scoped_model = self.class
   ov.send(:generate_overlap_sql_values, self)
   ov.send(:generate_overlap_sql_conditions, self)
   ov.send(:add_attributes, self, scope)

   ov.scoped_model.where([ov.sql_conditions, ov.sql_values])
end
```

**Comment by robinbortlik** [comment]
@johnmosesman @stricte @milankubin guys, I will take a look on it during a weekend. I'm now really busy with my work. Sorry guys.

**Comment by robinbortlik** [comment]
Hi guys, as I promised, there is a way how to get overlapped_records

https://github.com/robinbortlik/validates_overlap#overlapped-records .

It is not ideal solution, but more like hotfix.

**Comment by robinbortlik** [comment]
Yeah, and I forgot to mention. I released a new version on rubygems, so you can simply update gem to version `0.8.0` .
