### ISSUE TITLE
Explanation

### ISSUE THREAD

**Issue by atomical** [robinbortlik/validates_overlap#32]
Hi,

Could you add an explanation of what this does to the readme? Does this exist somewhere else?

Adam

**Comment by robinbortlik** [comment]
Hi Adam, can you be more concrete please? Do you mean, add to readme the description of this gem purpose?

**Comment by atomical** [comment]
Yes. I'd like to know what sort of problem the gem is solving and how it is solving it.

**Comment by voyera** [comment]
@atomical  this gem helps ensuring two records from the same models don't overlap in time.

Example: Record 1 has start_date Dec 1st and end_date of Dec 7th

Record 2 with a start_date Desc 3rd and end_date of Dec 10th would overlap with the first record and raise an error when using this gem.

**Comment by robinbortlik** [comment]
Thanks @voyera for explanation. I also added short sentence to readme. https://github.com/robinbortlik/validates_overlap#when-this-gem-should-be-helpful-for-you
