### ISSUE TITLE
Rails 6 scoping deprecation warning

### ISSUE THREAD

**Issue by kreintjes** [robinbortlik/validates_overlap#51]
Since Rails 6 using the overlap validation gives a deprecation warning when calling ActiveRecord's find_or_create_by:

```
DEPRECATION WARNING: Class level methods will no longer inherit scoping from `create` in Rails 6.1. To continue using the scoped relation, pass it into the block directly. To instead access the full set of models, as Rails 6.1 will, use `Model.unscoped`. (called from __pry__ at (pry):19)
```

To repoduce, suppose we have an ActiveRecord model:

```
class Model < ApplicationRecord
  validates :starts_at, :ends_at, overlap: true
end
```

Then calling `Model.find_or_create_by(...)` or `Model.find_or_create_by!(...)` results in the deprecation warning. It doesn't matter which attributes are given as long as there isn't a record with those attributes yet and a create is attempted. The warning does not occur when using find_or_initialize_by.

More information about the deprecation warning: https://github.com/rails/rails/pull/35280

**Comment by robinbortlik** [comment]
Hi @kreintjes , 

thank you for reporting this issue. I'm very busy with other stuff now, but hopefully I will be able to fix it before 6.1 release. 
In any case, pull requests are welcome.

**Comment by robinbortlik** [comment]
Hi @kreintjes , please try version 1.0 . Thank you @kamipo for contribution.

**Comment by kreintjes** [comment]
Will do. Thanks for the update and thanks @kamipo for the quick fix!

**Comment by kreintjes** [comment]
Works like a charm. Thanks again!
